{{- if .Values.istio.enabled -}}
{{- $egress := .Values.istio.egress -}}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- range $egress }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ $fullName }}
  labels: {{ $labels | nindent 4 }}
spec:
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
    {{- range .ports }}
    - number: {{ .number }}
      name: {{ .protocol | lower }}
      protocol: {{ .protocol | upper }}
    {{- end }}
  resolution: DNS
{{- end -}}
{{- end -}}